services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
        Sylius\Component\Resource\Model\ResourceInterface:
            autowire: false

    MonsieurBiz\SyliusSettingsPlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MonsieurBiz\SyliusSettingsPlugin\Form\:
        resource: '../../Form'
        tags: ['form.type']

    MonsieurBiz\SyliusSettingsPlugin\Processor\:
        resource: '../../Processor'

    MonsieurBiz\SyliusSettingsPlugin\Factory\Form\:
        resource: '../../Factory/Form'

    MonsieurBiz\SyliusSettingsPlugin\Twig\Extension\:
        resource: '../../Twig/Extension'
        tags: ['twig.extension']

    MonsieurBiz\SyliusSettingsPlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

    MonsieurBiz\SyliusSettingsPlugin\Menu\SettingsFormMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: monsieurbiz.settings.admin.update.form }

    monsieurbiz.settings.metadata_registry:
        class: MonsieurBiz\SyliusSettingsPlugin\Settings\Metadata\Registry

    MonsieurBiz\SyliusSettingsPlugin\Settings\Metadata\RegistryInterface: '@monsieurbiz.settings.metadata_registry'

    monsieurbiz.settings.registry:
        class: MonsieurBiz\SyliusSettingsPlugin\Settings\Registry

    MonsieurBiz\SyliusSettingsPlugin\Settings\RegistryInterface: '@monsieurbiz.settings.registry'

    monsieurbiz.settings.provider:
      class: MonsieurBiz\SyliusSettingsPlugin\Provider\SettingsProvider

    MonsieurBiz\SyliusSettingsPlugin\Provider\SettingsProviderInterface: '@monsieurbiz.settings.provider'
    
    MonsieurBiz\SyliusSettingsPlugin\Fixture\:
        resource: '../../Fixture'
